//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUser
    {
        public SiteUser()
        {
            this.Comments = new HashSet<Comment>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int PostCount { get; set; }
        public string SignupIp { get; set; }
        public string AvatarUrl { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
